### ISSUE TITLE
Add back some common `Justfile` commands to top-level

### ISSUE THREAD

**Issue by joshuadavidthomas** [westerveltco/django-twc-project#205]
In general, I like the move of tool-specific commands to the `just` submodules. But it did make a few of the more common commands a bit longer and more annoying to call (e.g. `just docker start` vs. `just start`). I want to open this issue for collecting any that should be aliased back in the root `Justfile`.

(Though looks like you can't actually "alias" a submodule command, so we'll have to create a new command that only action is calling that subcommand.)

**Comment by joshuadavidthomas** [comment]
Current top-level commands:

| Command | Description |
| --- | --- |
| `bootstrap` | Prepare local environment by installing dependencies and building Docker containers |
| `clean` | Delete cache, coverage, and dependency directories and stop and delete Docker containers including volumes |
| `console` | Open a Docker container's runtime console (e.g. a Python REPL, `psql`, etc.) |
| `server` | Start the Docker Compose application stack in the foreground |
| `setup` | Clean and bootstrap local environment, start Docker Compose stack, run Django migrations and create superuser account, and run tests, type checkers, and linters |
| `shell` | Open a bash shell in a Docker container |
| `test` | Run all project tests, including generating code coverage |
| `update` | Pull latest Docker images, lock Python and Node dependencies, and bootstrap local environment |

Here are the subcommands I find myself using pretty much daily:

| Subcommand(s) | Reason |
| --- | --- |
| `just dj makemigrations`, `just dj manage $COMMAND`, and `just dj migrate` | The most common Django management commands|
| `just dj shell` |  Prefer this to `just console app` as it runs using django-extensions` `shell_plus` |
| `just docker logs $CONTAINER` | See below |
| `just docker start` | I prefer to start the Docker Compose stack in the background and use the two docker log commands when I need to |
| `just docker stop` | When I just want to stop the Docker Compose stack, but don't want the nuclear option of `just clean` |
| `just docker tail $CONTAINER` | See above |
| `just node lock` and `just py lock` | |
| `just node upgrade` and `just py upgrade` | |
| `just project lint` | Lint the project, 'nuff said |

Alternatively, I rarely run these top-level commands:

- `just console`: See `just dj shell` above
- `just server`: See the `just docker` subcommands above

**Comment by joshuadavidthomas** [comment]
Based on my personal experience and opinion, I think these should be added to the top-level:

| Command | Subcommand(s) to call |
| --- | --- |
| `console dj` | `just dj shell` |
| `lint` | `just project lint` |
| `lock` | `just node lock` and `just py lock` |
| `logs $CONTAINER` | `just docker logs $CONTAINER` |
| `migrate` | `just dj migrate` |
| `makemigrations` (w/ `mm` alias) | `just dj makemigrations` |
| `manage $COMMAND` | `just dj manage $COMMAND` |
| `start` | `just docker start` |
| `stop` | `just docker stop` |
| `tail $CONTAINER` | `just docker tail $CONTAINER` |
| `upgrade` | `just node upgrade` and `just py upgrade` |

So the complete list of new top-level commands would be:

- `bootstrap`
- `clean`
- `console`
- `lint`
- `lock`
- `logs`
- `migrate`
- `makemigrations`/`mm`
- `manage`
- `server`
- `setup`
- `shell`
- `start`
- `stop`
- `tail`
- `test`
- `update`
- `upgrade`

**Comment by jefftriplett** [comment]
These perma-live in my `git stash`:

```
---- minerals --- 

diff --git a/Justfile b/Justfile
index e60a4e2..26e89ed 100644
--- a/Justfile
+++ b/Justfile
@@ -22,15 +22,24 @@ default:
 
 # Install and update all dependencies
 bootstrap:
-    @just docker build
+    # @just docker build
     @just py install
-    @just node install
+    # @just node install
+
+@build:
+    @just docker build
 
 # Clean up local development environment
 clean:
     @just project clean
     @just docker clean
 
+@down:
+    @just docker down
+
+lint:
+    @just project lint
+
 # Open a bash shell within a specified container (default: 'app')
 shell CONTAINER="app":
     @just docker run {{ CONTAINER }} "" "/bin/bash"
@@ -74,6 +83,10 @@ test:
     @just py test
     @just py coverage-html
 
+# Start development server
+up:
+    @just docker up
+
 # Update local development environment
 update:
     @just docker pull


---- spi ----

diff --git a/Justfile b/Justfile
index e60a4e2..7eccc54 100644
--- a/Justfile
+++ b/Justfile
@@ -26,11 +26,17 @@ bootstrap:
     @just py install
     @just node install
 
+@build:
+    @just docker build
+
 # Clean up local development environment
 clean:
     @just project clean
     @just docker clean
 
+@down:
+    @just docker down
+
 # Open a bash shell within a specified container (default: 'app')
 shell CONTAINER="app":
     @just docker run {{ CONTAINER }} "" "/bin/bash"
@@ -69,11 +75,18 @@ console CONTAINER="app" COMMAND="":
     COMMAND="${COMMAND:-/bin/bash}"
     just docker run {{ CONTAINER }} "" $COMMAND
 
+@lint:
+    @just project lint
+
 # Run all tests
 test:
     @just py test
     @just py coverage-html
 
+# Start development server
+up:
+    @just docker up
+
 # Update local development environment
 update:
     @just docker pull
```

**Comment by joshuadavidthomas** [comment]
Yeah, not 100% on that as well. I guess in my mind shell -> bash, which is why it's the way it is. But I could go the other way too.

**Comment by joshuadavidthomas** [comment]
And it is a bit confusing that `just console app` gets a Python REPL, but `just dj shell` gets a Python REPL with `shell_plus` loaded.

**Comment by joshuadavidthomas** [comment]
Also while we're at it, we may want to chuck a `cibuild` in there as well, which is one of the commands that was originally mentioned in the "Scripts To Rule Them All" blog post. 

Refs #170

**Comment by jefftriplett** [comment]
I debated adding `just bash` but I wanted to future-proof it in case bash6 comes out and changes everything. 😆

**Comment by jefftriplett** [comment]
With sub-commands, my brain likes seeing `just bootstrap` call `just {x} boostrap` and `just {y} bootstrap` for some of the basics. 

I played with looping over sub-commands, but it didn't quite seem worth the effort.

**Comment by joshuadavidthomas** [comment]
> I debated adding `just bash` but I wanted to future-proof it in case bash6 comes out and changes everything. 😆

HM! I'm okay with this.

So `just shell` becomes what `just console` is right now and opens an application's interactive REPL/psql/node shell/etc...

And `just console` becomes `just bash` and opens a bash shell in a container.

On the plus side, out of context `just bash` is a great sequence of words 😆

**Comment by joshuadavidthomas** [comment]
This is some quality bike-shedding we got going on.

**Comment by jefftriplett** [comment]
If you want to alias `bash` to `console` then have at it. I would leave `console` because I have years of muscle memory built up already :)

**Comment by jefftriplett** [comment]
While we are touching these, we could fix the `JUST_UNSTABLE` to either use Just's built-in `set unstable := True` or set `JUST_UNSTABLE` in the Justfile. 

Why? This saves a step in the docs that is confusing. Most of Just's unstable features are years long. Many have existed longer than the project did without them.

**Comment by joshuadavidthomas** [comment]
> While we are touching these, we could fix the `JUST_UNSTABLE` to either use Just's built-in `set unstable := True` or set `JUST_UNSTABLE` in the Justfile.
> 
> Why? This saves a step in the docs that is confusing. Most of Just's unstable features are years long. Many have existed longer than the project did without them.

I.. didn't realize you could do that? 😳

**Comment by joshuadavidthomas** [comment]
https://github.com/casey/just#modules1190

> `mod` statements were stabilized in `just`<sup>1.31.0</sup>. In earlier
versions, you'll need to use the `--unstable` flag, **`set unstable`**, or set the
`JUST_UNSTABLE` environment variable to use them.

Ugh, it's _right there_. 🤦

**Comment by joshuadavidthomas** [comment]
But also it looks like it's stable now so it might now be needed. Just make a note that you must be using at least Just version > 1.31.0, otherwise you'll have to do the unstable workaround.

**Comment by joshuadavidthomas** [comment]
I'll probably still just use `set unstable := True` anyway.

**Comment by jefftriplett** [comment]
I see it when I run `just --fmt` or `just fmt` which maybe is stable now...

**Comment by joshuadavidthomas** [comment]
Taken care of in #271
