### ISSUE TITLE
Swap `console` and `shell` Just commands

### ISSUE THREAD

**Issue by joshuadavidthomas** [westerveltco/django-twc-project#251]
Raised in #205 by @jefftriplett and I think he makes a good point.

**Comment by jefftriplett** [comment]
https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExN3JuMGVpaW13Zm9rNWl6dDN5eW8xODd4cHZ1OWhlNnQ4cW1oZGl3aCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/2A75RyXVzzSI2bx4Gj/giphy.gif
