### ISSUE TITLE
🤔 `just deploy` or `just prod` 

### ISSUE THREAD

**Issue by jefftriplett** [westerveltco/django-twc-project#304]
I was struggling to remember how to get files sftped up on Fly earlier and then I stumbled around remembering how to even get to a console `fly ssh console`. 

That made me realize we might want to address this via a just recipe.

**Comment by jefftriplett** [comment]
Feel free to move this to the proper repo/issue list btw.

**Comment by joshuadavidthomas** [comment]
Are we talking about actually deploying the applications or moving files up to the fly app? Or both?

**Comment by jefftriplett** [comment]
> Are we talking about actually deploying the applications or moving files up to the fly app? Or both?

both. 

Some of these might be useful and something we can standardize: 

- `just prod deploy`
- `just prod console`
- `just prod run...`
- `just prod upload ...`
